services:
  ollama:
    container_name: ollama_v5
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - "./ollamadata:/root/.ollama"
      - "./start.sh:/start.sh"  # Mount the script into the container
    ports:
      - "11434:11434"
    entrypoint: /start.sh
    privileged: true  # Enable privileged mode for the container
    # networks:
    #   - net

  chatbot:
    container_name: chatbot_v5
    build:
      context: ./    # The directory where Dockerfile and code are located
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - BASE_URL=http://ollama:11434     # Chatbot will access the Ollama API
    ports:
      - "8501:8501"                      
    depends_on:
      - ollama
    privileged: true  # Enable privileged mode for the container
    # networks:
    #   - net

# networks:
#   net:
#     driver: bridge
