services:
  ollama:
    container_name: ollama_v5
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - "./ollamadata:/root/.ollama"
      - "./ollama-entrypoint.sh:/ollama-entrypoint.sh"
    ports:
      - "11434:11434"
    entrypoint: /ollama-entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  chatbot:
    container_name: chatbot_v5
    build:
      context: ./ # The directory where Dockerfile and code are located
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - BASE_URL=http://ollama:11434
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
